services:
  - type: web
    name: ocr-project
    env: python
    pythonVersion: 3.13
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr &&
      pip install -r Beckend/requirements.txt &&
      cd Fronted/sr-client &&
      npm install &&
      npm run build &&
      cp -r dist/sr-client/browser/* ../../Beckend/static/
    startCommand: cd Beckend && uvicorn main:app --host 0.0.0.0 --port 10000
    routes:
      - path: /
        dest: /
